name: "Run CI"

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - "**"
      - "!gh-pages"

jobs:
  code-checks:
    if: ${{ github.event_name == 'push' || (github.event.pull_request.head.repo.full_name != 'docling-project/docling-metrics') }}
    uses: ./.github/workflows/job-checks.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  build-wheels:
    if: ${{ github.event_name == 'push' || (github.event.pull_request.head.repo.full_name != 'docling-project/docling-metrics') }}
    uses: ./.github/workflows/wheels.yml
    with:
      publish: false
      package: docling-metric-hello-world-cpp
